server:
  port: 8888  # El puerto típico para un config server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PxyReaper/config-service.git
          username: PXyReaper
          password: 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
          clone-on-start: true
          default-label: master   # <-- Aquí bien indentado bajo git
